Repository aerogear/graphback, pull requests merged in 2020-06, with the labels that each got.

#1567 test: add mongo db integration test
  .circleci/config.yml
  .gitignore
  integration/.graphqlrc.yml
  integration/package.json
  integration/tests/__snapshots__/runtime-workflow-postgres.ts.snap
  integration/tests/runtime-workflow-mongo.ts
  integration/tests/runtime-workflow-postgres.ts
  packages/graphback-core/src/plugin/GraphbackPluginEngine.ts
Labels: tests

#1586 refactor: avoid creating a new context object when adding options
  packages/graphback-codegen-schema/src/SchemaCRUDPlugin.ts
  packages/graphback-datasync/src/DataSyncPlugin.ts
Labels: enhancement

#1611 fix(graphql-migrations): map list to JSON
  integration/mock.graphql
  integration/tests/__snapshots__/runtime-workflow-postgres.ts.snap
  integration/tests/runtime-workflow-mongo.ts
  integration/tests/runtime-workflow-postgres.ts
  packages/graphback-runtime-knex/tests/service/db.sqlite
  packages/graphql-migrations/src/migrate.ts
Labels: bug
