Repository aerogear/graphback, pull requests merged in 2020-10, with the labels that each got.

#2143 docs(website): add announcement blog post
  website/blog/2020-10-01-announcing-graphback-1.0.md
  website/static/img/graphqlcrud-query-getone.gif
Labels: docs

#2161 build(changelog): add a changelog generator
  docs/CHANGELOG-0.x.md
  docs/CHANGELOG.md
  docs/releases.md
  package.json
  scripts/prepareRelease.sh
  website/versioned_docs/version-1.0/CHANGELOG.md
Labels: internal

#2153 feat(templates): add a Fastify template
  .vscode/launch.json
  package.json
  packages/create-graphback/src/init/components.ts
  packages/create-graphback/src/init/starterTemplates.ts
  packages/create-graphback/src/init/templateMetadata.ts
  templates/.eslintrc.json
  templates/ts-fastify-mongodb-backend/.env
  templates/ts-fastify-mongodb-backend/.gitignore
  templates/ts-fastify-mongodb-backend/.graphqlrc.yml
  templates/ts-fastify-mongodb-backend/Dockerfile
  templates/ts-fastify-mongodb-backend/README.md
  templates/ts-fastify-mongodb-backend/client
  templates/ts-fastify-mongodb-backend/docker-compose.yml
  templates/ts-fastify-mongodb-backend/model/datamodel.graphql
  templates/ts-fastify-mongodb-backend/package.json
  templates/ts-fastify-mongodb-backend/readme-diagram.png
  templates/ts-fastify-mongodb-backend/src/customContext.ts
  templates/ts-fastify-mongodb-backend/src/db.ts
  templates/ts-fastify-mongodb-backend/src/generated-types.ts
  templates/ts-fastify-mongodb-backend/src/index.ts
  templates/ts-fastify-mongodb-backend/src/resolvers/noteResolvers.ts
  templates/ts-fastify-mongodb-backend/src/schema/schema.graphql
  templates/ts-fastify-mongodb-backend/tsconfig.json
Labels: Hacktoberfest

#2171 fix(codegen-schema): remove auto primary key from create input
  docs/crud/mutations.md
  packages/graphback-codegen-schema/src/definitions/schemaDefinitions.ts
  packages/graphback-codegen-schema/tests/GraphQLSchemaCreator.test.ts
  packages/graphback-codegen-schema/tests/__snapshots__/GraphQLSchemaCreator.test.ts.snap
  packages/graphback-core/src/db/getPrimaryKey.ts
  packages/graphback-datasync/tests/__snapshots__/DataSyncPlugin.test.ts.snap
  packages/graphback-runtime-knex/tests/data/db.sqlite
  packages/graphql-serve/tests/__snapshots__/printSchema.test.ts.snap
  templates/ts-apollo-mongodb-backend/src/generated-types.ts
  templates/ts-apollo-mongodb-backend/src/schema/schema.graphql
Labels: bug
